$(document).ready(function() {
    $('.owl-carousel').owlCarousel({
        loop:true, 
        margin:42, 
        nav:false, 
        autoplay:true, 
        smartSpeed:2000, 
        autoplayTimeout:3500, 
        responsive:{ 
            0:{
                items:1
            },
            200:{
                items:2
            },
            500:{
                items:3
            },
            600:{
                items:4
            },
            800:{
                items:5
            },
            1000:{
                items:6
            }
        }
    });
});